# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Test changes
on:
  push:
    branches: [main]
jobs:
  release:
    name: Test recent changes
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4
      - name: Install a flaked Nix
        uses: DeterminateSystems/nix-installer-action@v12
      - name: Perform unit tests
        run: |
          (cd calendar && nix develop -c npm test)
